version: '3.9'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: donerhub
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user"]
      interval: 10s
      retries: 3
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 3

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    env_file: .env
    depends_on:
      - postgres
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 10s
      retries: 3
    ports:
      - "8000:8000"

  client_bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    command: python -m bot.client_bot.main
    env_file: .env
    depends_on:
      - fastapi
      - redis
    healthcheck:
      test: ["CMD", "python", "-m", "bot.client_bot.main", "--healthcheck"]
      interval: 10s
      retries: 3

  employee_bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    command: python -m bot.employee_bot.main
    env_file: .env
    depends_on:
      - fastapi
      - redis
    healthcheck:
      test: ["CMD", "python", "-m", "bot.employee_bot.main", "--healthcheck"]
      interval: 10s
      retries: 3

  admin_bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    command: python -m bot.admin_bot.main
    env_file: .env
    depends_on:
      - fastapi
      - redis
    healthcheck:
      test: ["CMD", "python", "-m", "bot.admin_bot.main", "--healthcheck"]
      interval: 10s
      retries: 3

  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - fastapi
    ports:
      - "80:80"
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 10s
      retries: 3

volumes:
  db_data:
