name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install deps
        run: |
          python -m pip install -r requirements.txt
      - name: Run tests
        run: pytest --cov
      - name: Docker build
        run: docker build -f Dockerfile.fastapi .
      - name: Docker push
        if: github.ref == 'refs/heads/main'
        run: echo "Pushing to registry"
